# Generated by Django 6.0.2 on 2026-04-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255)),
                ('end_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_end', to='map.building')),
                ('start_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='map.building')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='accounts.profile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_comment', to='map.route')),
            ],
        ),
    ]
