# Generated by Django 6.0.2 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('coordinate_latitude', models.FloatField()),
                ('coordinate_longitude', models.FloatField()),
            ],
        ),
    ]
